import type { MediaAsset } from "./types";

export function buildInspirationPrompt(media: MediaAsset[], platform: string, mood: string, description: string) {
  const assets = media.map((asset, index) => ({
    index: index + 1,
    name: asset.originalName,
    durationSec: asset.durationSec,
    size: asset.sizeBytes,
    resolution: asset.width && asset.height ? `${asset.width}x${asset.height}` : "unknown",
    fps: asset.fps,
    tags: asset.tags,
    inferredUse: asset.bestUse,
    lensProfile: asset.lensProfile,
    directorNote: asset.directorNote,
    visualSummary: asset.visualSummary,
    visualTags: asset.visualTags,
    visualMood: asset.visualMood,
    visualHook: asset.visualHook,
    visibleSubjects: asset.visibleSubjects,
    sceneType: asset.sceneType,
    visualConfidence: asset.visualConfidence,
    visionStatus: asset.visionStatus,
  }));

  return [
    "你是一个短视频剪辑灵感导演，不是剪辑软件操作员。",
    "你的任务是根据用户素材档案，提出可执行的剪辑灵感、故事方向、开头钩子、字幕风格和剪辑注意事项。",
    "不要写泛泛的鸡汤，不要假设不存在的画面。所有建议都要尽量引用素材名称或素材类型。",
    "输出必须是严格 JSON，不要 Markdown，不要额外解释。",
    "",
    "JSON 结构：",
    "{",
    '  "ideas": [{"title": string, "platform": string, "durationSec": number, "mood": string, "hook": string, "structure": string[], "recommendedAssets": string[], "musicSuggestion": string, "effectSuggestions": string[], "materialMatchScore": number, "noviceScore": number, "publishPotentialScore": number, "difficultyScore": number, "recommendationReason": string}],',
    '  "timeline": [{"assetName": string, "durationSec": number, "purpose": string, "subtitle": string, "effect": string}],',
    '  "report": {"summary": string, "diagnosis": {"storyPotentialScore": number, "editingDifficulty": "简单" | "中等" | "偏难", "verdict": string, "bestOpeningAssets": [{"assetName": string, "reason": string}], "mustUseAssets": [{"assetName": string, "reason": string}], "optionalAssets": [{"assetName": string, "reason": string}], "missingShots": string[], "recommendedRouteTitle": string, "whyThisRoute": string}, "materialMap": [{"category": string, "count": number, "assetNames": string[], "insight": string}], "hookBank": string[], "titleBank": string[], "styleRecipes": [{"name": string, "rhythm": string, "color": string, "subtitle": string, "sound": string}], "audioGuide": {"musicDirection": string, "soundHooks": string[], "beatPlan": string[]}, "captionGuide": {"tone": string, "openingLines": string[], "transitionLines": string[], "endingLines": string[], "rules": string[]}, "visualGuide": {"colorDirection": string, "rhythmDirection": string, "coverIdeas": string[], "effectIdeas": string[]}, "blindSpots": string[], "remixPrompts": string[], "nextActions": string[]}',
    "}",
    "",
    "约束：",
    "- ideas 必须正好 3 个，方向要明显不同。",
    "- ideas 每条路线必须给 0-100 的 materialMatchScore、noviceScore、publishPotentialScore、difficultyScore。difficultyScore 越高表示越难。",
    "- report.diagnosis 是素材体检报告，必须先判断这批素材能剪成什么、缺什么、先剪哪条路线。",
    "- diagnosis.bestOpeningAssets、mustUseAssets、optionalAssets 必须引用素材名称，reason 要解释为什么。",
    "- diagnosis.recommendedRouteTitle 必须对应 ideas 里的一个 title。",
    "- timeline 是灵感执行清单，不是让用户在本产品里剪辑。",
    "- report.materialMap 建议 4 类：开场瞬间、氛围转场、记忆点、收束镜头。",
    "- hookBank、titleBank、blindSpots、remixPrompts、nextActions 各给 3-5 条。",
    "- audioGuide、captionGuide、visualGuide 必须结合素材档案给具体建议，不能写成通用教程。",
    "- 如果素材档案里有 visualSummary、visibleSubjects、visualMood、visualHook，必须优先引用这些视觉理解，不要只根据文件名猜测。",
    "- 如果 visionStatus 不是 ready，要明确降低判断确定性，不要假装已经看懂画面。",
    "- 风格配方给 2 条即可。",
    "",
    `用户目标平台：${platform}`,
    `用户目标风格：${mood}`,
    `用户描述：${description || "用户还没有补充描述，请根据素材档案给出保守建议。"}`,
    `素材档案：${JSON.stringify(assets, null, 2)}`,
  ].join("\n");
}
